# @format

name: First Workflow
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo greeting
        run: echo 'hello world'
      - name: echo check packages
        run: |
          echo 'node version' node -v
          echo 'npm version' npm -v
      - name: python Command
        run: |
          import platform
          print (platform.processor())
        shell: python
